//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzuredbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datosdinamico
    {
        public string NombreID { get; set; }
        public Nullable<int> simulacionID { get; set; }
        public string Datastring { get; set; }
        public Nullable<long> DataInt { get; set; }
    
        public virtual Simulacione Simulacione { get; set; }
    }
}
