//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzuredbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiante()
        {
            this.EstudiantesGrupos = new HashSet<EstudiantesGrupos>();
            this.SimmulacionEstudiantes = new HashSet<SimmulacionEstudiante>();
        }
    
        public string EstudianteID { get; set; }
        public string EstNombre { get; set; }
        public string EstApellido { get; set; }
        public Nullable<int> EstIDMoodle { get; set; }
        public string EstTotalNota { get; set; }
        public string EstReporte { get; set; }
        public string EstMatricula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudiantesGrupos> EstudiantesGrupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimmulacionEstudiante> SimmulacionEstudiantes { get; set; }
    }
}
