//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzuredbConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCHEMICALLABEntities : DbContext
    {
        public DBCHEMICALLABEntities()
            : base("name=DBCHEMICALLABEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datosdinamico> Datosdinamicos { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<EstudiantesGrupos> EstudiantesGrupos { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Profesore> Profesores { get; set; }
        public virtual DbSet<SimmulacionEstudiante> SimmulacionEstudiantes { get; set; }
        public virtual DbSet<Simulacione> Simulaciones { get; set; }
    }
}
