//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzuredbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimmulacionEstudiante
    {
        public long SimEstId { get; set; }
        public Nullable<int> SimulacionId { get; set; }
        public string EstudianteId { get; set; }
        public string Nota { get; set; }
        public string desc { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Simulacione Simulacione { get; set; }
    }
}
